# Generated by Django 4.1.7 on 2023-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('1', 'Suggestion'), ('2', 'Bug'), ('3', 'Other')], default='default', max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('details', models.TextField(max_length=1500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
